###############################################################################
#                               GNMI INPUT PLUGIN                             #
###############################################################################
[[inputs.gnmi]]
  addresses = [ ${ACX_ADDRESSES} ]
  username = "${GNMI_USERNAME}"
  password = "${GNMI_PASSWORD}" 
  tls_enable = true
  insecure_skip_verify = true
  encoding = "proto"
  redial = "60s"
  path_guessing_strategy = "subscription"
  depth = 1

# TAGS excluded
  tagexclude = ["path", "host", "system_id" ]

# FIELDS excluded
  fieldexclude = [
    # /components/component/transceiver
    "physical_channels/channel/index",
    "physical_channels/channel/state/associated_optical_channel",
    "physical_channels/channel/state/description",
    "physical_channels/channel/state/index",
    "physical_channels/channel/state/output_frequency",
    "physical_channels/channel/state/target_output_power",
    "physical_channels/channel/state/tx_laser",
    "property/state/configurable",
    "state/connector_type",
    "state/date_code",
    "state/enabled",
    "state/ethernet_pmd",
    "state/ethernet_pmd_preconf",
    "state/fault_condition",
    "state/fec_mode",
    "state/fec_status",
    "state/form_factor",
    "state/form_factor_preconf",
    "state/line_port",
    "state/module_functional_type",
    "state/otn_compliance*",
    "state/present",
    "state/serial_no",
    "state/sonet_sdh_compliance*",
    "state/vendor*",
    "thresholds/threshold/*"
    
  ] 

    [inputs.gnmi.aliases]
      OPTIC = "/interfaces/interface/optics"

# Temperature sensor
    [[inputs.gnmi.subscription]]
      name = "TEMP"
      path = "/components/component/state/temperature/instant"
      subscription_mode = "sample"
      sample_interval = "60s"

# Optic sensor
    [[inputs.gnmi.subscription]]
      name = "OPTIC"
      path = "/components/component/transceiver"
      subscription_mode = "sample"
      sample_interval = "60s"

# Optical channel sensor
    [[inputs.gnmi.subscription]]
      name = "OCH"
      path = "/components/component/optical-channel"
      subscription_mode = "sample"
      sample_interval = "60s"

# Properties (various sensors)
     [[inputs.gnmi.subscription]]
      name = "PROPERTIES"
      path = "/components/component/properties"
      subscription_mode = "sample"
      sample_interval = "60s"
