###############################################################################
#                               RENAME PLUGIN                                 #
###############################################################################
[[processors.rename]]
  order = 100
  [[processors.rename.replace]]
    tag = "name"
    dest = "sensor"
  [[processors.rename.replace]]
    tag = "source"
    dest = "device"

# TEMP sensors
[[processors.rename]]
  order = 102
  namepass = ["TEMP"]
  [[processors.rename.replace]]
    field = "instant"
    dest = "current"
  [[processors.rename.replace]]
    field = "temp_value"
    dest = "current"

#OPTIC sensors
[[processors.rename]]
  order = 103
  namepass = ["OPTIC"]
  [[processors.rename.replace]]
    field = "physical_channels/channel/state/input_power/instant"
    dest = "physical_channels_input_power"
  [[processors.rename.replace]]
    field = "physical_channels/channel/state/output_power/instant"
    dest = "physical_channels_output_power"
  [[processors.rename.replace]]
    field = "physical_channels/channel/state/laser_bias_current/instant"
    dest = "physical_channels_laser_bias_current"
  [[processors.rename.replace]]
    field = "state/input_power/instant"
    dest = "input_power"
  [[processors.rename.replace]]
    field = "state/output_power/instant"
    dest = "output_power"
  [[processors.rename.replace]]
    field = "state/laser_bias_current/instant"
    dest = "laser_bias_current"
  [[processors.rename.replace]]
    field = "state/fec_corrected_bits"
    dest = "fec_corrected_bits"
  [[processors.rename.replace]]
    field = "state/fec_uncorrectable_blocks"
    dest = "fec_uncorrectable_blocks"