{
 "title": "Drops and errors",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Interface errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(INTERFACES_in_errors{}[$__rate_interval]) >0",
     "legendFormat": "in {{device}} {{sensor}}"
    },
    {
     "expr": "rate(INTERFACES_in_fcs_errors{}[$__rate_interval]) >0",
     "legendFormat": "fcs {{device}} {{sensor}}"
    }
   ]
  },
  {
   "title": "System drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(PROPERTIES_Packet_dropped_due_to_congestion{}[$__rate_interval]) >0",
     "legendFormat": "congestion {{device}} {{sensor}}"
    },
    {
     "expr": "rate(PROPERTIES_Packets_dropeed_due_to_Invalid_Destination{}[$__rate_interval]) >0",
     "legendFormat": "inv dest  {{device}} {{sensor}}"
    },
    {
     "expr": "rate(PROPERTIES_Packets_dropped_in_Ingress_Traffic_Managers{}[$__rate_interval]) >0",
     "legendFormat": "in tm {{device}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(QUEUE_dropped_pkts{}[$__rate_interval]) >0",
     "legendFormat": "{{device}} {{interface_id}} q{{sensor}}"
    },
    {
     "expr": "rate(INTERFACES_out_queue_hp_red_drop_pkts{}[$__rate_interval]) >0",
     "legendFormat": "hp red {{device}} {{sensor}} q{{queue_number}}"
    },
    {
     "expr": "rate(INTERFACES_out_queue_lp_red_drop_pkts{}[$__rate_interval]) >0",
     "legendFormat": "lp red {{device}} {{sensor}} q{{queue_number}}"
    },
    {
     "expr": "rate(INTERFACES_out_queue_red_drop_pkts{}[$__rate_interval]) >0",
     "legendFormat": "red {{device}} {{sensor}} q{{queue_number}}"
    },
    {
     "expr": "rate(INTERFACES_out_queue_tail_drop_pkts{}[$__rate_interval]) >0",
     "legendFormat": "tail {{device}} {{sensor}} q{{queue_number}}"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(PROPERTIES_hwds_tcp_error{}[$__rate_interval]) >0",
     "legendFormat": "hwds tcp {{device}} {{sensor}}"
    },
    {
     "expr": "rate(PROPERTIES_hwds_data_error{}[$__rate_interval]) >0",
     "legendFormat": "hwds data {{device}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Interface out errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(INTERFACES_out_errors{}[$__rate_interval]) >0",
     "legendFormat": "out {{device}} {{sensor}}"
    }
   ]
  }
 ]
}