{
 "title": "MPLS TE",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device", "query": { "query": "label_values(LSP_bytes,device)" } },
   {
    "name": "lsp",
    "query": {
     "query": "label_values(LSP_bytes{device=~\"$device\"},sensor)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(RSVP_reserved_bandwidth{device=\"$device\"},interface_id)"
    }
   },
   {
    "name": "phy",
    "query": {
     "query": "label_values(RSVP_reserved_bandwidth{interface_id=\"$interface\"},interface_id)"
    }
   },
   {
    "name": "unit",
    "query": {
     "query": "label_values(RSVP_reserved_bandwidth{interface_id=~\"$interface\"},interface_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LSPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$lsp traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "LSP_signaled_bandwidth{lsp=\"${lsp}\"}",
     "legendFormat": "resv"
    },
    {
     "expr": "LSP_jnx_byte_rate{device=\"$device\",sensor=\"$lsp\"}*8",
     "legendFormat": "rate"
    },
    {
     "expr": "quantile_over_time(0.95, rate(LSP_bytes{sensor=\"${lsp}\"}*8)[1h])",
     "legendFormat": "byte_avg"
    }
   ]
  },
  {
   "title": "$lsp packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "LSP_signaled_bandwidth{lsp=\"${lsp}\"}",
     "legendFormat": "resv"
    },
    {
     "expr": "LSP_jnx_packet_rate{device=\"$device\",sensor=\"$lsp\"}",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "$device LSPs traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "LSP_jnx_byte_rate{device=\"$device\"}*8 >0",
     "legendFormat": "{{lsp}}"
    }
   ]
  },
  {
   "title": "$device LSP traffic stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "LSP_jnx_byte_rate{device=\"$device\"}*8 >0",
     "legendFormat": "{{lsp}}"
    }
   ]
  },
  {
   "title": "Interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "$interface reserved bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "repeat": "unit",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "RSVP_reserved_bandwidth{device=\"${device}\", interface_id=\"${interface}\", priority=\"0\"}",
     "legendFormat": "RSVP resv"
    },
    {
     "expr": "rate(SUBINTERFACES_out_octets{device=\"$device\",sensor=\"$phy\", index=\"$unit\"}[$__rate_interval]*8)",
     "legendFormat": "traffic out"
    }
   ]
  },
  {
   "title": "Interface reserved bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "RSVP_reserved_bandwidth{device=\"${device}\", interface_id=~\"ge-.*|xe-.*|et-.*|ae.*\", priority=\"0\"}*1000",
     "legendFormat": "{{interface_id}}"
    }
   ]
  },
  {
   "title": "Interface reservations count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "RSVP_active_reservations_count{device=\"mx-poz-2\", interface_id=~\"ge-.*|xe-.*|et-.*|ae.*\"}",
     "legendFormat": "{{interface_id}}"
    }
   ]
  }
 ]
}