{
 "title": "Optic",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {
     "query": "label_values(OPTIC_input_power,device)"
    }
   },
   {
    "name": "FPC",
    "query": {
     "query": "label_values(OPTIC_input_power{device=\"$device\"},sensor)"
    }
   },
   {
    "name": "PIC",
    "query": {
     "query": "label_values(OPTIC_input_power{device=\"$device\"},sensor)"
    }
   },
   {
    "name": "PORT",
    "query": {
     "query": "label_values(OPTIC_input_power{device=\"$device\"},sensor)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Receive $device port $FPC/$PIC/$PORT",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "OPTIC_input_power{device=\"$device\", sensor=~\"FPC$FPC:PIC$PIC:PORT$PORT:.*\" }",
     "legendFormat": "rx {{sensor}}"
    },
    {
     "expr": "OPTIC_physical_channels_input_power{device=\"$device\",sensor=~\"FPC$FPC:PIC$PIC:PORT$PORT:.*\"}",
     "legendFormat": "phy rx {{sensor}}-{{index}}"
    }
   ]
  },
  {
   "title": "Transmit $device port $FPC/$PIC/$PORT",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "OPTIC_output_power{device=\"$device\", sensor=~\"FPC$FPC:PIC$PIC:PORT$PORT:.*\" }",
     "legendFormat": "tx {{sensor}}"
    },
    {
     "expr": "OPTIC_physical_channels_output_power{device=\"$device\",sensor=~\"FPC$FPC:PIC$PIC:PORT$PORT:.*\"}",
     "legendFormat": "phy tx {{sensor}}-{{index}}"
    }
   ]
  },
  {
   "title": "Transceiver temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "TEMP_current{device=~\"$device\", sensor=~\"(FPC$FPC:PIC$PIC:PORT$PORT:.*)|(FPC$FPC-xcvr-$FPC/$PIC/$PORT)\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}